# Generated by Django 3.2.18 on 2023-12-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
