# Generated by Django 3.2.18 on 2023-12-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0006_auto_20231203_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='text',
            field=models.CharField(default='', max_length=140),
        ),
    ]
