# Generated by Django 3.2.18 on 2023-12-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0007_education_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='text',
            new_name='effect',
        ),
    ]
