# Generated by Django 5.0 on 2023-12-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0009_effect_remove_subject_effects_alter_education_effect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='effects',
        ),
        migrations.AlterField(
            model_name='education',
            name='effect',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='subject',
            name='effects',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
    ]
