# Generated by Django 5.0 on 2023-12-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0010_remove_subject_effects_alter_education_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uczelnia.department'),
        ),
    ]
