# Generated by Django 5.0 on 2023-12-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0012_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.FloatField(choices=[(2.0, '2.0'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=2.0),
        ),
    ]
