# Generated by Django 5.0 on 2023-12-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0013_alter_education_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ects_points',
            field=models.IntegerField(default=0, verbose_name='Punkty ECTS'),
        ),
    ]
