# Generated by Django 5.0 on 2024-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0014_subject_ects_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fist_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
