# Generated by Django 5.0 on 2024-01-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0015_remove_customuser_fist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=9),
        ),
    ]
