# Generated by Django 5.0 on 2024-01-17 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczelnia', '0016_alter_customuser_address_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uczelnia.department'),
            preserve_default=False,
        ),
    ]
